### ISSUE TITLE
TYPO/Bug? "The method wolrdExists(String) is undefined for the type WorldUtils"

### ISSUE THREAD

**Issue by SandUhrGucker** [dervonnebe/FarmweltPlugin#2]
FarmweltPlugin (1.0.0), Multiverse-Core (4.3.14),Paper 1.21.4-32, Java21  starts, but if I type /farmwelt I get

```
[13:59:57 INFO]: SandUhrGucker joined the game
[13:59:57 INFO]: SandUhrGucker[/XXX.XXX.XXX.XXX:38046] logged in with entity id 25 at ([NiceWorld120]121.5, 93.0, 1163.5)
[14:00:03 INFO]: SandUhrGucker issued server command: /farmwelt
[14:00:03 ERROR]: Command exception: /farmwelt
org.bukkit.command.CommandException: Unhandled exception executing command 'farmwelt' in plugin FarmweltPlugin v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:105) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.commands.Commands.performCommand(Commands.java:326) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2197) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2170) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-32-b8a0541]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.Error: Unresolved compilation problem:
        The method wolrdExists(String) is undefined for the type WorldUtils

        at FarmweltPlugin-1.0.0.jar/de.codingtt.farmweltplugin.commands.FarmweltCommand.onCommand(FarmweltCommand.java:52) ~[FarmweltPlugin-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        ... 27 more
>
[14:00:20 INFO]: Stopping server
[14:00:20 INFO]: [FarmweltPlugin] Disabling FarmweltPlugin v1.0.0
```

I wonder about "The method **wolrdExists**(String) is undefined for the type WorldUtil", because it seems you fixed it already in Commit 9c0bf17

**Comment by dervonnebe** [comment]
I will watch it as soon as I get home

**Comment by dervonnebe** [comment]
I will watch it as soon as I get home
